class NoUser(Exception): ...
class NoPasswd(Exception): ...
class NoData(Exception): ...
class NoSelectDatabase(Exception): ...
class ExeceedLimit(Exception): ...


# Catch Exception
class CatchSystemTypeError(Exception): ...

# Init Resolver Exception
class ConfigOptionsIsNoFound(Exception): ...
class ConfigAttributeNoFound(Exception): ...
